# ndarray Object Internals
The NumPy ndarray provides a means to interpret a block of homogeneous data as a multidimensional array object. The data type, or dtype determines how the data is interpreted as being floating point, integer, boolean, or any of the other types that NumPy provides. The ndarray is a generic multidimensional container for homogeneous data; all of the elements must be the same type.

Part of what makes ndarray powerful is that every array object is a strided view on a block of data. The strides are the number of bytes to step in each dimension when traversing an array. For example, a (100, 200) array of float64s has strides (800, 8) meaning that to move to the next row, one needs to skip 800 bytes, and to move to the next column, one needs to skip 8 bytes.

# NumPy dtype Hierarchy

In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import matplotlib.animation as animation
import time
import random 
import math
import sys
import os 


ints = np.ones(10, dtype=np.int32) 
floats = np.ones(10, dtype=np.float32) 
np.issubdtype(ints.dtype, np.integer) 

True

In [2]:
np.issubdtype(floats.dtype, np.float32) 

True

In [3]:
np.float64.mro()     # method resolution order 

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

# Advanced Array Manipulation 
There are many ways to work with arrays beyond fancy indexing, slicing, and simple reshaping. While much of the heavy lifting for data analysis applications is handled by higher level functions in pandas.

# Reshaping Arrays

In [4]:
arr = np.arange(8) 

In [5]:
arr 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
arr.reshape(4,2) 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [7]:
# a multidimensional array can also be reshaped: 
arr.reshape((4,2)).reshape(2,4) 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
# One of the passed shape dimensions can be -1, in which case the value used for that dimension will be inferred from the data: 

arr = np.arange(15) 

In [9]:
arr.reshape(5,-1) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
# since an array's shape attribute is a tuple, it can be passed to reshape, too: 
other_arr = np.ones((3,5)) 
other_arr.shape

(3, 5)

In [11]:
arr.reshape(other_arr.shape) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
# The Opposite operation of reshape from one-dimensional array is to higher dimensional array is typically known as flattening or raveling. 
arr = np.arange(15).reshape(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])