# Numerical Python: numpy 

The NumPy package provides the "ndarray" object for efficient storage and manipulation of dense data arrays in Python. 

The ndarray is similar to the Python list, but can store data of any dimension. 

The elements of a ndarray are all of the same type, and indexed by a tuple of positive integers.

In NumPy dimensions are called axes. The number of axes is rank. 

The ndarray class is also known by the alias array.

In [3]:
import numpy as np 
data = np.random.randn(2, 3) 

In [4]:
data

array([[ 0.11229047, -0.60959023, -0.41856589],
       [ 1.24049198, -1.14652732,  0.97703514]])

In [5]:
data.ndim 

2

In [6]:
data.shape

(2, 3)

In [7]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_) 
numeric_strings.astype(float) 

array([ 1.25, -9.6 , 42.  ])

In [14]:
int_array = np.arange(10) 

In [15]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64) 
calibers.dtype 

dtype('float64')

In [18]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Operations between Arrays and Scalars 
A vectorized operation is performed on the elements of two arrays on an element-by-element basis. 
Arrays are important because they enable you to express batch operations on data
without writing any for loops. This is usually called vectorization. Any arithmetic operations
between equal-size arrays applies the operation elementwise:

In [19]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
arr * arr 

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [21]:
arr-arr 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
1/arr 

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [23]:
arr ** 0.5 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

# Basic Indexing and Slicing 

In [24]:
arr2=np.arange(10) 

In [25]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr2[5:8] 

array([5, 6, 7])

In [27]:
arr2[5:8] = 12
arr2 

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [28]:
arr_slice = arr2[5:8]    
arr_slice[1] = 12345 
arr2 

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [29]:
arr_slice[:] = 64 

In [30]:
arr2 

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [31]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]]) 

In [32]:
arr2d 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2d.shape

(3, 3)

In [36]:
# With higher dimensional arrays, you have many more options. In a two-dimensional
# array, the elements at each index are no longer scalars but rather one-dimensional
# arrays:
arr2d[2] 

array([7, 8, 9])

In [37]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[0][2]

3

In [42]:
arr2d[2, 0] 

7

In [44]:
# In multidimensional arrays, if you omit later indices, the returned object will be a lowerdimensional
# ndarray consisting of all the data along the higher dimensions. So in the
# 2 × 2 × 3 array arr3d
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]) 

In [45]:
arr3d.shape

(2, 2, 3)

In [47]:
arr3d[0].shape

(2, 3)

In [48]:
old_values = arr3d[0].copy() 

In [49]:
arr3d[0] = 42 

In [50]:
arr3d 

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0]=old_values 
arr3d 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Indexing with slices p/89

In [52]:
# Like one-dimensional objects such as Python lists, ndarrays can be sliced using the
# familiar syntax: