# Numerical Python: numpy 

The NumPy package provides the "ndarray" object for efficient storage and manipulation of dense data arrays in Python. 

The ndarray is similar to the Python list, but can store data of any dimension. 

The elements of a ndarray are all of the same type, and indexed by a tuple of positive integers.

In NumPy dimensions are called axes. The number of axes is rank. 

The ndarray class is also known by the alias array.

In [3]:
import numpy as np 
data = np.random.randn(2, 3) 

In [4]:
data

array([[ 0.11229047, -0.60959023, -0.41856589],
       [ 1.24049198, -1.14652732,  0.97703514]])

In [5]:
data.ndim 

2

In [6]:
data.shape

(2, 3)

In [7]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_) 
numeric_strings.astype(float) 

array([ 1.25, -9.6 , 42.  ])

In [14]:
int_array = np.arange(10) 

In [15]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64) 
calibers.dtype 

dtype('float64')

In [18]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Operations between Arrays and Scalars 
A vectorized operation is performed on the elements of two arrays on an element-by-element basis. 
Arrays are important because they enable you to express batch operations on data
without writing any for loops. This is usually called vectorization. Any arithmetic operations
between equal-size arrays applies the operation elementwise:

In [19]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
arr * arr 

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])